// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fajdcqfhcyegerfatwei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhamRjcWZoY3llZ2VyZmF0d2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDk5NjksImV4cCI6MjA3MTI4NTk2OX0.XUyChEpy5e0k7eqAdaL_zZtc7YHS-ktqq2VpFZ8Ww4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});